//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class MyFramework_ManagerContorBase_MyFramework_LuaManagerModelWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(MyFramework.ManagerContorBase<MyFramework.LuaManagerModel>), typeof(MyFramework.ManagerContorBase), "ManagerContorBase_MyFramework_LuaManagerModel");
		L.RegFunction("LoadEnd", LoadEnd);
		L.RegFunction("Load", Load);
		L.RegFunction("New", _CreateMyFramework_ManagerContorBase_MyFramework_LuaManagerModel);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Instance", get_Instance, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateMyFramework_ManagerContorBase_MyFramework_LuaManagerModel(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				MyFramework.ManagerContorBase<MyFramework.LuaManagerModel> obj = new MyFramework.ManagerContorBase<MyFramework.LuaManagerModel>();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: MyFramework.ManagerContorBase<MyFramework.LuaManagerModel>.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadEnd(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			MyFramework.ManagerContorBase<MyFramework.LuaManagerModel> obj = (MyFramework.ManagerContorBase<MyFramework.LuaManagerModel>)ToLua.CheckObject<MyFramework.ManagerContorBase<MyFramework.LuaManagerModel>>(L, 1);
			bool o = obj.LoadEnd();
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Load(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			MyFramework.ManagerContorBase<MyFramework.LuaManagerModel> obj = (MyFramework.ManagerContorBase<MyFramework.LuaManagerModel>)ToLua.CheckObject<MyFramework.ManagerContorBase<MyFramework.LuaManagerModel>>(L, 1);
			object[] arg0 = ToLua.ToParamsObject(L, 2, count - 1);
			obj.Load(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Instance(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, MyFramework.ManagerContorBase<MyFramework.LuaManagerModel>.Instance);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

