//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class MyFramework_AppPathConfigWrap
{
	public static void Register(LuaState L)
	{
		L.BeginStaticLibs("AppPathConfig");
		L.RegVar("mAppExternalAddress", get_mAppExternalAddress, null);
		L.RegVar("mAppResourcesTemp", get_mAppResourcesTemp, null);
		L.RegVar("mVersionAddress", get_mVersionAddress, null);
		L.RegVar("ExternalAssetTail", get_ExternalAssetTail, null);
		L.RegVar("PlatformRoot", get_PlatformRoot, null);
		L.RegVar("GetstreamingAssetsPath", get_GetstreamingAssetsPath, null);
		L.RegVar("AppLuaAddress", get_AppLuaAddress, null);
		L.RegVar("AppAssetBundleTemp", get_AppAssetBundleTemp, null);
		L.RegVar("AppAssetBundleAddress", get_AppAssetBundleAddress, null);
		L.EndStaticLibs();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_mAppExternalAddress(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, MyFramework.AppPathConfig.mAppExternalAddress);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_mAppResourcesTemp(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, MyFramework.AppPathConfig.mAppResourcesTemp);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_mVersionAddress(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, MyFramework.AppPathConfig.mVersionAddress);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ExternalAssetTail(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, MyFramework.AppPathConfig.ExternalAssetTail);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PlatformRoot(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, MyFramework.AppPathConfig.PlatformRoot);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_GetstreamingAssetsPath(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, MyFramework.AppPathConfig.GetstreamingAssetsPath);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_AppLuaAddress(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, MyFramework.AppPathConfig.AppLuaAddress);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_AppAssetBundleTemp(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, MyFramework.AppPathConfig.AppAssetBundleTemp);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_AppAssetBundleAddress(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, MyFramework.AppPathConfig.AppAssetBundleAddress);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

