//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class MyFramework_LuaHelpToolsWrap
{
	public static void Register(LuaState L)
	{
		L.BeginStaticLibs("LuaHelpTools");
		L.RegFunction("Find", Find);
		L.RegFunction("OnSubmit", OnSubmit);
		L.RegFunction("AddClick", AddClick);
		L.RegFunction("AddEvent", AddEvent);
		L.RegVar("GetManager_ManagerModel", get_GetManager_ManagerModel, null);
		L.RegVar("GetViewManagerModel", get_GetViewManagerModel, null);
		L.EndStaticLibs();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Find(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 1, typeof(UnityEngine.GameObject));
			string arg1 = ToLua.CheckString(L, 2);
			UnityEngine.GameObject o = MyFramework.LuaHelpTools.Find(arg0, arg1);
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnSubmit(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 1, typeof(UnityEngine.GameObject));
			string arg1 = ToLua.CheckString(L, 2);
			string arg2 = ToLua.CheckString(L, 3);
			UnityEngine.Component o = MyFramework.LuaHelpTools.OnSubmit(arg0, arg1, arg2);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddClick(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 1, typeof(UnityEngine.GameObject));
			string arg1 = ToLua.CheckString(L, 2);
			LuaFunction arg2 = ToLua.CheckLuaFunction(L, 3);
			MyFramework.LuaHelpTools.AddClick(arg0, arg1, arg2);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddEvent(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 1, typeof(UnityEngine.GameObject));
			string arg1 = ToLua.CheckString(L, 2);
			UnityEngine.EventSystems.EventTriggerType arg2 = (UnityEngine.EventSystems.EventTriggerType)ToLua.CheckObject(L, 3, typeof(UnityEngine.EventSystems.EventTriggerType));
			LuaFunction arg3 = ToLua.CheckLuaFunction(L, 4);
			MyFramework.LuaHelpTools.AddEvent(arg0, arg1, arg2, arg3);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_GetManager_ManagerModel(IntPtr L)
	{
		try
		{
			ToLua.Push(L, MyFramework.LuaHelpTools.GetManager_ManagerModel);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_GetViewManagerModel(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, MyFramework.LuaHelpTools.GetViewManagerModel);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

