//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class MyFramework_LuaModelControlBaseWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(MyFramework.LuaModelControlBase), typeof(MyFramework.ManagerContorBase));
		L.RegFunction("LoadEnd", LoadEnd);
		L.RegFunction("Start", Start);
		L.RegFunction("Close", Close);
		L.RegFunction("AddComp", AddComp);
		L.RegFunction("LoadResourceComp", LoadResourceComp);
		L.RegFunction("Load", Load);
		L.RegFunction("New", _CreateMyFramework_LuaModelControlBase);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateMyFramework_LuaModelControlBase(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				string arg0 = ToLua.CheckString(L, 1);
				MyFramework.LuaModelControlBase obj = new MyFramework.LuaModelControlBase(arg0);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: MyFramework.LuaModelControlBase.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadEnd(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			MyFramework.LuaModelControlBase obj = (MyFramework.LuaModelControlBase)ToLua.CheckObject<MyFramework.LuaModelControlBase>(L, 1);
			bool o = obj.LoadEnd();
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Start(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			MyFramework.LuaModelControlBase obj = (MyFramework.LuaModelControlBase)ToLua.CheckObject<MyFramework.LuaModelControlBase>(L, 1);
			object[] arg0 = ToLua.CheckObjectArray(L, 2);
			obj.Start(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Close(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			MyFramework.LuaModelControlBase obj = (MyFramework.LuaModelControlBase)ToLua.CheckObject<MyFramework.LuaModelControlBase>(L, 1);
			obj.Close();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddComp(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			MyFramework.LuaModelControlBase obj = (MyFramework.LuaModelControlBase)ToLua.CheckObject<MyFramework.LuaModelControlBase>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			string arg1 = ToLua.CheckString(L, 3);
			object[] arg2 = ToLua.ToParamsObject(L, 4, count - 3);
			MyFramework.ModelCompBase o = obj.AddComp(arg0, arg1, arg2);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadResourceComp(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			MyFramework.LuaModelControlBase obj = (MyFramework.LuaModelControlBase)ToLua.CheckObject<MyFramework.LuaModelControlBase>(L, 1);
			obj.LoadResourceComp();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Load(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			MyFramework.LuaModelControlBase obj = (MyFramework.LuaModelControlBase)ToLua.CheckObject<MyFramework.LuaModelControlBase>(L, 1);
			object[] arg0 = ToLua.ToParamsObject(L, 2, count - 1);
			obj.Load(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

