//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class MyFramework_AppConfigWrap
{
	public static void Register(LuaState L)
	{
		L.BeginStaticLibs("AppConfig");
		L.RegFunction("SetAppConfig", SetAppConfig);
		L.RegVar("ResFileSuffix", get_ResFileSuffix, set_ResFileSuffix);
		L.RegVar("AppResModel", get_AppResModel, set_AppResModel);
		L.RegVar("AppLanguage", get_AppLanguage, set_AppLanguage);
		L.RegVar("TargetPlatform", get_TargetPlatform, set_TargetPlatform);
		L.EndStaticLibs();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetAppConfig(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			MyFramework.AppResModel arg0 = (MyFramework.AppResModel)ToLua.CheckObject(L, 1, typeof(MyFramework.AppResModel));
			MyFramework.Language arg1 = (MyFramework.Language)ToLua.CheckObject(L, 2, typeof(MyFramework.Language));
			MyFramework.AppPlatform arg2 = (MyFramework.AppPlatform)ToLua.CheckObject(L, 3, typeof(MyFramework.AppPlatform));
			MyFramework.WebRootAddress arg3 = (MyFramework.WebRootAddress)ToLua.CheckObject(L, 4, typeof(MyFramework.WebRootAddress));
			MyFramework.AppConfig.SetAppConfig(arg0, arg1, arg2, arg3);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ResFileSuffix(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, MyFramework.AppConfig.ResFileSuffix);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_AppResModel(IntPtr L)
	{
		try
		{
			ToLua.Push(L, MyFramework.AppConfig.AppResModel);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_AppLanguage(IntPtr L)
	{
		try
		{
			ToLua.Push(L, MyFramework.AppConfig.AppLanguage);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_TargetPlatform(IntPtr L)
	{
		try
		{
			ToLua.Push(L, MyFramework.AppConfig.TargetPlatform);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_ResFileSuffix(IntPtr L)
	{
		try
		{
			string arg0 = ToLua.CheckString(L, 2);
			MyFramework.AppConfig.ResFileSuffix = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_AppResModel(IntPtr L)
	{
		try
		{
			MyFramework.AppResModel arg0 = (MyFramework.AppResModel)ToLua.CheckObject(L, 2, typeof(MyFramework.AppResModel));
			MyFramework.AppConfig.AppResModel = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_AppLanguage(IntPtr L)
	{
		try
		{
			MyFramework.Language arg0 = (MyFramework.Language)ToLua.CheckObject(L, 2, typeof(MyFramework.Language));
			MyFramework.AppConfig.AppLanguage = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_TargetPlatform(IntPtr L)
	{
		try
		{
			MyFramework.AppPlatform arg0 = (MyFramework.AppPlatform)ToLua.CheckObject(L, 2, typeof(MyFramework.AppPlatform));
			MyFramework.AppConfig.TargetPlatform = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

