//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class MyFramework_LuaModelControlBase_MyFramework_LuaServiceModelWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(MyFramework.LuaModelControlBase<MyFramework.LuaServiceModel>), typeof(MyFramework.LuaModelControlBase), "LuaModelControlBase_MyFramework_LuaServiceModel");
		L.RegFunction("New", _CreateMyFramework_LuaModelControlBase_MyFramework_LuaServiceModel);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateMyFramework_LuaModelControlBase_MyFramework_LuaServiceModel(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				MyFramework.LuaModelControlBase<MyFramework.LuaServiceModel> obj = new MyFramework.LuaModelControlBase<MyFramework.LuaServiceModel>();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else if (count == 1)
			{
				string arg0 = ToLua.CheckString(L, 1);
				MyFramework.LuaModelControlBase<MyFramework.LuaServiceModel> obj = new MyFramework.LuaModelControlBase<MyFramework.LuaServiceModel>(arg0);
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: MyFramework.LuaModelControlBase<MyFramework.LuaServiceModel>.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

